#!/usr/bin/env bash

if rfkill list bluetooth | grep -q "Soft blocked: yes"; then
    rfkill unblock bluetooth
    bluetoothctl power on

    notify-send "Bluetooth On" --icon "network-bluetooth-activated" \
        --hint "string:x-canonical-private-synchronous:bluetooth"
else
    bluetoothctl power off
    rfkill block bluetooth

    notify-send "Bluetooth Off" --icon "network-bluetooth-inactive" \
        --hint "string:x-canonical-private-synchronous:bluetooth"
fi

