#!/usr/bin/env bash

# Dependency checks
command -v powerprofilesctl >/dev/null 2>&1 || { echo "powerprofilesctl not found"; exit 1; }
if ! command -v notify-send >/dev/null 2>&1; then
  notify_send_missing=true
fi

current_profile="$(powerprofilesctl get 2>/dev/null)"

tooltip=""

case $current_profile in
    performance)
        tooltip="  Performance"
        ;;
    balanced)
        tooltip="  Balanced"
        ;;
    power-saver)
        tooltip="  Power Saver"
        ;;
esac

echo $(jq -n \
    --arg text "$current_profile" \
    --arg alt "$current_profile" \
    --arg tooltip "$tooltip" \
    --arg class "$current_profile" \
    '{text: $text, alt: $alt, tooltip: $tooltip, class: $class}')
